### ISSUE TITLE
Issues with pretrained model for RefCOCO

### ISSUE THREAD

**Issue by spandanagella** [lichengunc/MAttNet#29]
If we use the pretrained model for RefCOCO ((i.e., output/refcoco_unc/mrcn_cmr_with_st.pth) ) and execute the script experiments/scripts/eval_easy.sh", it throws an error saying that state-dict is missing a few keys. Could you please let us know if we are missing anything here. Please find the detailed error below:

Traceback (most recent call last):
  File "./tools/eval_easy.py", line 105, in <module>
    evaluate(params)
  File "./tools/eval_easy.py", line 46, in evaluate
    model = load_model(model_path, model_opt)
  File "./tools/eval_easy.py", line 29, in load_model
    model.load_state_dict(checkpoint['model'].state_dict())
  File "/home/arjunakula/anaconda3/envs/pytorch_0.4.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for JointMatching:
Missing key(s) in state_dict: "sub_encoder.att_fuse.1.num_batches_tracked", "sub_matching.vis_emb_fc.1.num_batches_tracked", "sub_matching.vis_emb_fc.5.num_batches_tracked", "sub_matching.lang_emb_fc.1.num_batches_tracked", "sub_matching.lang_emb_fc.5.num_batches_tracked", "loc_matching.vis_emb_fc.1.num_batches_tracked", "loc_matching.vis_emb_fc.5.num_batches_tracked", "loc_matching.lang_emb_fc.1.num_batches_tracked", "loc_matching.lang_emb_fc.5.num_batches_tracked", "rel_matching.vis_emb_fc.1.num_batches_tracked", "rel_matching.vis_emb_fc.5.num_batches_tracked", "rel_matching.lang_emb_fc.1.num_batches_tracked", "rel_matching.lang_emb_fc.5.num_batches_tracked". 

2) We were able to download the parsed attributes (R1-R7) and use them in inference (in the sub-module refer-parse2).  However while training, we couldn't generate new attributes. Are we supposed to run the script for  'parsing expression using stanford parser' before running the script for 'parsing expression using Vicente's R1-R7 attributes'? Also, running the script for 'parsing expression using stanford parser' takes forever to complete? Some of the scripts are depending on a module called `baseParser' which is not found in the code?

**Comment by jshi31** [comment]
The same question

**Comment by jshi31** [comment]
Solved.
For your first question, change `model.load_state_dict(checkpoint['model'].state_dict())` to `model.load_state_dict(checkpoint['model'].state_dict(), strict=False)`, then it can normally loaded. This is due to the higher version of pytorch.

**Comment by spandanagella** [comment]
Thank you this helped the first issue.

**Comment by jshi31** [comment]
@spandanagella I find that my evaluation result is only 36%. Can you reproduce the evaluation result?
It might be the problem introduced by BatchNorm1d, which require the parameter `num_batches_tracked` in 0.4.0 but not in 0.3.0.

**Comment by lichengunc** [comment]
Hi jshi31, you are right. The pytorch I used for this project was 0.2. I didn't test it with the latest version since then, so the easiest way to evaluate it is to downgrade your pytorch version. Someday I will look back this project and update everything to modern versions. :-)

**Comment by jshi31** [comment]
I compared config1: python3.6 + pytorch0.4.0 and config2: python2.7 + pytorch0.3.1. The config2 gives the reported result but config1 not. I find the data.json generated by `tools/prepro.py` has different list order in these two configs, which causes the difference in evaluation accuracy. However, the model itself should work in both configs.

**Comment by lichengunc** [comment]
Thanks @jshi31 . Yeah, this may due to the issue of old python. I may use the keys of a dictionary to build some index. Older python may not maintain the hash table (order). One way to address this is to save all necessary dictionaries and load them later.
