### ISSUE TITLE
ValueError: length of all samples has to be greater than 0, but found an element in 'lengths' that is <=0

### ISSUE THREAD

**Issue by chituma110** [lichengunc/MAttNet#5]
iter[550](epoch[0]), train_loss=0.555, lr=4.00E-04, data:0.63s/iter, model:0.46s/iter
Traceback (most recent call last):
  File "./tools/train.py", line 224, in <module>
    main(args)
  File "./tools/train.py", line 150, in main
    loss, T, wrapped = lossFun(loader, optimizer, model, mm_crit, att_crit, opt, iter)
  File "./tools/train.py", line 64, in lossFun
    labels)
  File "/home/amax/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/cqs/MAttNet/tools/../lib/layers/joint_match.py", line 177, in forward
    context, hidden, embedded = self.rnn_encoder(labels)
  File "/home/amax/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/data2/cqs/MAttNet/tools/../lib/layers/lang_encoder.py", line 59, in forward
    embedded = nn.utils.rnn.pack_padded_sequence(embedded, sorted_input_lengths_list, batch_first=True)
  File "/home/amax/miniconda2/lib/python2.7/site-packages/torch/nn/utils/rnn.py", line 54, in pack_padded_sequence
    raise ValueError("length of all samples has to be greater than 0, "
ValueError: length of all samples has to be greater than 0, but found an element in 'lengths' that is <=0

**Comment by lichengunc** [comment]
This error maybe due to some incoming encoded sentence is all zeros. Could you check what sentence is it?

**Comment by chituma110** [comment]
@lichengunc I have run "python tools/prepro.py --dataset refcoco --splitBy unc" and I checked the length of sentence and got 5 zero-length sentence their id are 
147989
154736
156820
161366
169493

How can i do with these sentence?

**Comment by chituma110** [comment]
@lichengunc Why did the length of sentence become zero?

**Comment by dami23** [comment]
@chituma110 Hi, I also encountered this problem "/informatik2/tams/home/mi/Downloads/1.png". Did you find a resolution, could you please give me an advice about this error. Thank you!
