### ISSUE TITLE
Bug in tools/extract_mrcn_ann_feats.py

### ISSUE THREAD

**Issue by ChenyunWu** [lichengunc/MAttNet#6]
When I run:
`python tools/extract_mrcn_ann_feats.py --dataset refcoco --splitBy unc` 

I got the error:
```
Traceback (most recent call last):
  File "tools/extract_mrcn_ann_feats.py", line 143, in <module>
    main(args)
  File "tools/extract_mrcn_ann_feats.py", line 121, in main
    ann_pool5, ann_fc7 = ann_to_pool5_fc7(mrcn, ann, net_conv, im_info)
  File "tools/extract_mrcn_ann_feats.py", line 74, in ann_to_pool5_fc7
    fc7 = fc7.mean(3).mean(2)
RuntimeError: dimension out of range (expected to be in range of [-2, 1], but got 3)
```

Resolved by commenting out line 74: `fc7 = fc7.mean(3).mean(2)`.

**Comment by lichengunc** [comment]
Thanks!
