### ISSUE TITLE
The test accuracy in detected boxes isn't up to your submit, and i don't know why?

### ISSUE THREAD

**Issue by Keysmis** [lichengunc/MAttNet#8]
Hi, I'm running your code and model, found that the test accuracy in detected boxes isn't up to your submit, the strange thing is that when i use GT to test, the accuracy is good.  i don't know why, that seems my detect module is bad? i do have some issues in runing run_detect.py , when i run it, i got the cuda error:invalid function. that seems have a little problems in GPU computing, so i turn some function to cpu and return to gpu, but i don't think that make  something wrong, i check the code again still not find the error, do you have the same problems before? Thank you!

**Comment by Keysmis** [comment]
![1](https://user-images.githubusercontent.com/9586803/41753928-e166c274-7602-11e8-962d-770589c367e2.PNG)
![2](https://user-images.githubusercontent.com/9586803/41753930-e1cdb146-7602-11e8-9d60-8f8a6a5df471.PNG)
![3](https://user-images.githubusercontent.com/9586803/41753931-e2306f66-7602-11e8-9bc9-775eb6cf16a5.PNG)

**Comment by lichengunc** [comment]
Sorry this error is not clear to me. 
Could you try mask-rcnn (https://github.com/lichengunc/mask-faster-rcnn) going through its test first, and cv/mrcn_detection.ipynb in this repo?

**Comment by Keysmis** [comment]
Traceback (most recent call last):
  File "/home/qiang.w/anaconda2/lib/python2.7/site-packages/pudb-2017.1.4-py2.7.egg/pudb/__init__.py", line 93, in runscript
    dbg._runscript(mainpyfile)
  File "/home/qiang.w/anaconda2/lib/python2.7/site-packages/pudb-2017.1.4-py2.7.egg/pudb/debugger.py", line 432, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/home/qiang.w/anaconda2/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "pc_mrcn_detection.py", line 36, in <module>
    scores, boxes = mrcn.predict(img_path)
  File "../tools/../lib/mrcn/inference.py", line 100, in predict
    _, scores, bbox_pred, rois, net_conv = self.net.test_image(blobs['data'], blobs['im_info'])
  File "../tools/../pyutils/mask-faster-rcnn/lib/nets/network.py", line 571, in test_image
    self.forward(image, im_info, None, None, mode='TEST')
  File "../tools/../pyutils/mask-faster-rcnn/lib/nets/network.py", line 541, in forward
    net_conv, rois, cls_prob, bbox_pred, mask_prob = self._predict()
  File "../tools/../pyutils/mask-faster-rcnn/lib/nets/network.py", line 468, in _predict
    rois = self._region_proposal(net_conv)
  File "../tools/../pyutils/mask-faster-rcnn/lib/nets/network.py", line 256, in _region_proposal
    rois, _ = self._proposal_layer(rpn_cls_prob, rpn_bbox_pred)
  File "../tools/../pyutils/mask-faster-rcnn/lib/nets/network.py", line 94, in _proposal_layer
    self._feat_stride, self._anchors, self._num_anchors)
  File "../tools/../pyutils/mask-faster-rcnn/lib/layer_utils/proposal_layer.py", line 71, in proposal_layer
    blob = torch.cat((batch_inds, proposals), 1)
RuntimeError: cuda runtime error (8) : invalid device function at /pytorch/torch/lib/THC/THCGeneral.c:844

**Comment by Keysmis** [comment]
@lichengunc  i had run your cv/mrcn_detection.ipynb , and i got the cuda runtime error , i tried to turn it to cpu and return to gpu, i got zero detected boxes when compare with CONF_THRESH.

**Comment by Keysmis** [comment]
@lichengunc  
![default](https://user-images.githubusercontent.com/9586803/42496343-488111c2-8458-11e8-8dde-5f1da748330d.PNG)
![2](https://user-images.githubusercontent.com/9586803/42496344-48e19db2-8458-11e8-84e2-0074336bbe21.PNG)
i runed your example_demo file, and get the detected picture, i find it has less detected boxes compared with your submit in that file.

**Comment by lichengunc** [comment]
Just checked the demo again, everything's right on my side. Again, please check the testing of mask r-cnn (https://github.com/lichengunc/mask-faster-rcnn) first. I can't tell too much given this cuda error and the results (did you solve the cuda error issue by yourself?).
